apiVersion: apps/v1
kind: Deployment
metadata:
  name: assesmentapidep
  labels:
    app: assesmentapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assesmentapi
  template:
    metadata:
      name: assesmentapik8s
      labels:
        env: prod
        app: assesmentapi
        app.kubernetes.io/name: assesmentapi
    spec:
      containers:
        - name: assesmentapi
          image:  zieglernattacatalyst/xphyruscreationapi
          ports:
            - name: assesment-port
              containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: assesment-lb
# spec:
#   selector:
#     app.kubernetes.io/name: authapi
#   ports:
#     - name: assesment-lb-port
#       port: 8080
#       targetPort: 80
#       protocol: TCP
#   type: LoadBalancer
  

#working, dont touch