apiVersion: v1
kind: Service
metadata:
  name: assesmentapi
spec:
  type: ClusterIP
  selector:
    app: assesmentapi
  ports:
    - name: assesmentapi
      protocol: TCP
      port: 80
      targetPort: 80
    
#authservice-cip:80  put this in appsett.prod.json for url

#authapi:80 for metadata__name: authapi