// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xphyrus.CreationAPI.Data;

#nullable disable

namespace Xphyrus.AssesmentAPI.Migrations
{
    [DbContext(typeof(ApplicatioDbContext))]
    [Migration("20230823000524_initMig")]
    partial class initMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.COnstraint", b =>
                {
                    b.Property<int>("COnstraintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("COnstraintId"));

                    b.Property<string>("CodingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Constraint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("COnstraintId");

                    b.HasIndex("CodingId");

                    b.ToTable("constrainss");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.Coding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InputFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Coding");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.EvliationCase", b =>
                {
                    b.Property<string>("EvliationCaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InputCase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputCase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvliationCaseId");

                    b.HasIndex("CodingId");

                    b.ToTable("evliationCases");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.Example", b =>
                {
                    b.Property<int>("ExampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExampleId"));

                    b.Property<string>("CodingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Explaination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExampleId");

                    b.HasIndex("CodingId");

                    b.ToTable("examples");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.MasterCode", b =>
                {
                    b.Property<int>("MasterCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterCodeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.HasKey("MasterCodeId");

                    b.HasIndex("CodingId");

                    b.ToTable("MasterCode");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.COnstraint", b =>
                {
                    b.HasOne("Xphyrus.CreationAPI.Models.Coding", null)
                        .WithMany("Constrains")
                        .HasForeignKey("CodingId");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.EvliationCase", b =>
                {
                    b.HasOne("Xphyrus.CreationAPI.Models.Coding", null)
                        .WithMany("EvliationCases")
                        .HasForeignKey("CodingId");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.Example", b =>
                {
                    b.HasOne("Xphyrus.CreationAPI.Models.Coding", null)
                        .WithMany("Examples")
                        .HasForeignKey("CodingId");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.MasterCode", b =>
                {
                    b.HasOne("Xphyrus.CreationAPI.Models.Coding", null)
                        .WithMany("Code")
                        .HasForeignKey("CodingId");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.Coding", b =>
                {
                    b.Navigation("Code");

                    b.Navigation("Constrains");

                    b.Navigation("EvliationCases");

                    b.Navigation("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
