// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xphyrus.AssesmentAPI.Data;

#nullable disable

namespace Xphyrus.AssesmentAPI.Migrations
{
    [DbContext(typeof(ApplicatioDbContext))]
    [Migration("20230829173431_Misclennaous")]
    partial class Misclennaous
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.Assesment", b =>
                {
                    b.Property<string>("AssesmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsStrict")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AssesmentId");

                    b.ToTable("Assesments");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.COnstraint", b =>
                {
                    b.Property<string>("COnstraintId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Constraint")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("COnstraintId");

                    b.HasIndex("CodingId");

                    b.ToTable("Constrainss");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.Coding", b =>
                {
                    b.Property<string>("CodingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssesmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InputFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodingId");

                    b.HasIndex("AssesmentId");

                    b.ToTable("Coding");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.EvliationCase", b =>
                {
                    b.Property<string>("EvliationCaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InputCase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputCase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvliationCaseId");

                    b.HasIndex("CodingId");

                    b.ToTable("EvliationCases");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.Example", b =>
                {
                    b.Property<string>("ExampleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Explaination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Output")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExampleId");

                    b.HasIndex("CodingId");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.MasterCode", b =>
                {
                    b.Property<string>("MasterCodeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.HasKey("MasterCodeId");

                    b.HasIndex("CodingId");

                    b.ToTable("MasterCode");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.COnstraint", b =>
                {
                    b.HasOne("Xphyrus.CreationAPI.Models.Coding", null)
                        .WithMany("Constrains")
                        .HasForeignKey("CodingId");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.Coding", b =>
                {
                    b.HasOne("Xphyrus.CreationAPI.Models.Assesment", null)
                        .WithMany("Codings")
                        .HasForeignKey("AssesmentId");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.EvliationCase", b =>
                {
                    b.HasOne("Xphyrus.CreationAPI.Models.Coding", null)
                        .WithMany("EvliationCases")
                        .HasForeignKey("CodingId");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.Example", b =>
                {
                    b.HasOne("Xphyrus.CreationAPI.Models.Coding", null)
                        .WithMany("Examples")
                        .HasForeignKey("CodingId");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.MasterCode", b =>
                {
                    b.HasOne("Xphyrus.CreationAPI.Models.Coding", null)
                        .WithMany("Code")
                        .HasForeignKey("CodingId");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.Assesment", b =>
                {
                    b.Navigation("Codings");
                });

            modelBuilder.Entity("Xphyrus.CreationAPI.Models.Coding", b =>
                {
                    b.Navigation("Code");

                    b.Navigation("Constrains");

                    b.Navigation("EvliationCases");

                    b.Navigation("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
