// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xphyrus.AssesmentAPI.Data;

#nullable disable

namespace Xphyrus.AssesmentAPI.Migrations
{
    [DbContext(typeof(ApplicatioDbContext))]
    [Migration("20230919105847_dataSimplification")]
    partial class dataSimplification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Xphyrus.AssesmentAPI.Models.Assesment", b =>
                {
                    b.Property<string>("AssesmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodingsCodingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsStrict")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AssesmentId");

                    b.HasIndex("CodingsCodingId");

                    b.ToTable("Assesments");
                });

            modelBuilder.Entity("Xphyrus.AssesmentAPI.Models.AssesmentAdmins", b =>
                {
                    b.Property<string>("AssesmentAdminsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssesmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasResultDeclared")
                        .HasColumnType("bit");

                    b.HasKey("AssesmentAdminsId");

                    b.ToTable("AssesmentAdmins");
                });

            modelBuilder.Entity("Xphyrus.AssesmentAPI.Models.AssesmentParticipant", b =>
                {
                    b.Property<string>("AssesmentParticipantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssesmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("HasStarted")
                        .HasColumnType("bit");

                    b.HasKey("AssesmentParticipantId");

                    b.ToTable("AssesmentParticipants");
                });

            modelBuilder.Entity("Xphyrus.AssesmentAPI.Models.COnstraint", b =>
                {
                    b.Property<string>("COnstraintId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Constraint")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("COnstraintId");

                    b.ToTable("Constrainss");
                });

            modelBuilder.Entity("Xphyrus.AssesmentAPI.Models.Coding", b =>
                {
                    b.Property<string>("CodingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Constrain1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Constrain2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Constrain3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodingId");

                    b.ToTable("Coding");
                });

            modelBuilder.Entity("Xphyrus.AssesmentAPI.Models.EvliationCase", b =>
                {
                    b.Property<string>("EvliationCaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InputCase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputCase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvliationCaseId");

                    b.HasIndex("CodingId");

                    b.ToTable("EvliationCases");
                });

            modelBuilder.Entity("Xphyrus.AssesmentAPI.Models.Example", b =>
                {
                    b.Property<string>("ExampleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Explaination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Output")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExampleId");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("Xphyrus.AssesmentAPI.Models.MasterCode", b =>
                {
                    b.Property<string>("MasterCodeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.HasKey("MasterCodeId");

                    b.ToTable("MasterCode");
                });

            modelBuilder.Entity("Xphyrus.AssesmentAPI.Models.Assesment", b =>
                {
                    b.HasOne("Xphyrus.AssesmentAPI.Models.Coding", "Codings")
                        .WithMany()
                        .HasForeignKey("CodingsCodingId");

                    b.Navigation("Codings");
                });

            modelBuilder.Entity("Xphyrus.AssesmentAPI.Models.EvliationCase", b =>
                {
                    b.HasOne("Xphyrus.AssesmentAPI.Models.Coding", null)
                        .WithMany("EvliationCases")
                        .HasForeignKey("CodingId");
                });

            modelBuilder.Entity("Xphyrus.AssesmentAPI.Models.Coding", b =>
                {
                    b.Navigation("EvliationCases");
                });
#pragma warning restore 612, 618
        }
    }
}
