// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xphyrus.NexusAPI.Data;

#nullable disable

namespace Xphyrus.NexusAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicatioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Xphyrus.NexusAPI.Models.Admin", b =>
                {
                    b.Property<Guid>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NexusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AdminId");

                    b.HasIndex("NexusId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Xphyrus.NexusAPI.Models.CodingAssessment", b =>
                {
                    b.Property<Guid>("CodingAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NexusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodingAssessmentId");

                    b.HasIndex("NexusId");

                    b.ToTable("CodingAssessments");
                });

            modelBuilder.Entity("Xphyrus.NexusAPI.Models.Nexus", b =>
                {
                    b.Property<Guid>("NexusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NexusId");

                    b.ToTable("Nexus");
                });

            modelBuilder.Entity("Xphyrus.NexusAPI.Models.TestCase", b =>
                {
                    b.Property<Guid>("TestCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodingAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InputCase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputCase")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestCaseId");

                    b.HasIndex("CodingAssessmentId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("Xphyrus.NexusAPI.Models.Admin", b =>
                {
                    b.HasOne("Xphyrus.NexusAPI.Models.Nexus", "Nexus")
                        .WithMany("Admins")
                        .HasForeignKey("NexusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nexus");
                });

            modelBuilder.Entity("Xphyrus.NexusAPI.Models.CodingAssessment", b =>
                {
                    b.HasOne("Xphyrus.NexusAPI.Models.Nexus", "Nexus")
                        .WithMany("CodingAssessments")
                        .HasForeignKey("NexusId");

                    b.Navigation("Nexus");
                });

            modelBuilder.Entity("Xphyrus.NexusAPI.Models.TestCase", b =>
                {
                    b.HasOne("Xphyrus.NexusAPI.Models.CodingAssessment", "CodingAssessment")
                        .WithMany("TestCases")
                        .HasForeignKey("CodingAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodingAssessment");
                });

            modelBuilder.Entity("Xphyrus.NexusAPI.Models.CodingAssessment", b =>
                {
                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("Xphyrus.NexusAPI.Models.Nexus", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("CodingAssessments");
                });
#pragma warning restore 612, 618
        }
    }
}
